### ISSUE TITLE
Depth Input

### ISSUE THREAD

**Issue by dmasmont** [liyi14/mx-DeepIM#1]
Hello,

I can see in the code that depth information can be used as an input but I can find it reported in the paper. What is its function? Does using depth as input provides any improvement during training and/or testing?

Also, will the trained models be provided?
Thank you for your help

P.D: In page 5 in the paper it is reported that the fully connected are added after 11 convolutions. Shouldn't it be 10 convs?

**Comment by wangg12** [comment]
@dmasmont The depth is not used and we didn't find much improvement with depth input in our earlier expriments. The point is that our method aims to refine the 6D object poses without the need of depth.
It seems the 11 convolutions sould be 10 convolutions. It is a typo.

**Comment by dmasmont** [comment]
Hello @wangg12 , thank you your reply.
I am following the scripts to set up the data and I am facing some issues. 
There is a typo at prepare_data.md: instead of "python toolkit/LM6d_devkit/LM6d_adapt_real.py" it should be "python toolkit/LM6d_devkit/LM6d_1_adapt_real.py".

When using the rendering engine of glumpy, the code crashes when reading the texture maps at render_py.py or render_py_multi.py:
`        self.render_kernel['u_texture'] = np.copy(data.load("{}/texture_map.png"
                                                            .format(model_folder))[::-1, :, :])`

data.load() it is not loading the textures properly. It always returns a matrix of shape (512,512). Could that be because I am using a different version of glumpy? Maybe I am not generating the texture map properly?

Also after running "python toolkit/LM6d_devkit/LM6d_adapt_real.py" , when analyzing the generated label images of "'benchviseblue", the images contain multiple labels, while in the other categories there is only 1 label per image. Should that be the expected result?

Thank you

**Comment by wangg12** [comment]
@dmasmont The folder of "benchviseblue"(01) also contains the labels of Occluded LINEMOD dataset. In LINEMOD, only one label is used. So it is the expected result.

 As for the texture, how did you generate your texture? We generate it by meshlab.

**Comment by dmasmont** [comment]
hello @wangg12 , I am using meshlab following the recommended steps:
"1. open .ply file in meshlab
2. Filters/Texture/Parametrization: Trivial - Per Triangle
 (if you get an error about the inter-triangle border being too much, increase the texture dimension)
3. Then Filters/Texture/Transfer: Vertex Color to Texture
4. export mesh as textured.obj and points.xyz (for .xyz, uncheck the Normal option) "
When running "LM6d_3_gen_rendered.py" the rendered images in data/rendered_v1 only contain red dots:
![000001_0-color](https://user-images.githubusercontent.com/26934529/45788364-394fd300-bc48-11e8-8d7b-ca2c7206c962.png)

That is not the expected result, right?

**Comment by wangg12** [comment]
@dmasmont I don't know what is the problem. You could put your processed model and texture files somewhere, so I can have a look.

**Comment by dmasmont** [comment]
Hello @wangg12, glumpy.data.load() requires Pillow to load the texture_maps. I didn't have it installed but it wasn't returning any error, it just returned a (255,255) array. It looks its loading the images properly now
