### ISSUE TITLE
Python 3 undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by eyildiz-ugoe** [liyi14/mx-DeepIM#11]
After running:

`python3 experiments/deepim/deepim_train_test.py --cfg experiments/deepim/cfgs/deepim_flownet_LM_SIXD_v1_all_RFMx4_8epoch.yaml --gpus 0
`

one gets the error of:

```
  File "experiments/deepim/deepim_train_test.py", line 20, in <module>
    train.main()
  File "experiments/deepim/../../deepim/train.py", line 285, in main
    config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
  File "experiments/deepim/../../deepim/train.py", line 278, in train_net
    prefix=prefix)
  File "experiments/deepim/../../deepim/core/module.py", line 975, in fit
    from lib.pair_matching.batch_updater_py_multi import batchUpdaterPyMulti
  File "experiments/deepim/../../lib/pair_matching/batch_updater_py_multi.py", line 15, in <module>
    from lib.flow_c.flow import gpu_flow_wrapper
  File "experiments/deepim/../../lib/flow_c/flow.py", line 12, in <module>
    from lib.flow_c.gpu_flow import gpu_flow
ImportError: experiments/deepim/../../lib/flow_c/gpu_flow.so: undefined symbol: _Py_ZeroStruct
```

After taking a look into the issue on the Internet, it is likely that it's a Python 3 issue. You may want to delete that "Python 3.x should also be OK." from the main page.

**Comment by wangg12** [comment]
@eyildiz-ugoe How did you compile flow_c? It works fine for me with python3.

**Comment by wangg12** [comment]
@eyildiz-ugoe How did you compile flow_c? Python 3 works fine for me.

**Comment by eyildiz-ugoe** [comment]
I followed the instructions on the main page, that's it. Didn't specifically compile flow_c on my own.

**Comment by wangg12** [comment]
@eyildiz-ugoe Which file did you use to compile flow_c, `setup_linux.py` or `jit.py`?

**Comment by G-YY** [comment]
When I run sh train_and_test_deepim_ape.sh,I met the following error:
Traceback (most recent call last):
  File "experiments/deepim/deepim_train_test.py", line 21, in <module>
    train.main()
  File "experiments/deepim/../../deepim/train.py", line 437, in main
    config.TRAIN.lr_step,
  File "experiments/deepim/../../deepim/train.py", line 421, in train_net
    prefix=prefix,
  File "experiments/deepim/../../deepim/core/module.py", line 1154, in fit
    from lib.pair_matching.batch_updater_py_multi import batchUpdaterPyMulti
  File "experiments/deepim/../../lib/pair_matching/batch_updater_py_multi.py", line 12, in <module>
    from lib.flow_c.flow import gpu_flow_wrapper
  File "experiments/deepim/../../lib/flow_c/flow.py", line 15, in <module>
    from gpu_flow import gpu_flow
ImportError: No module named gpu_flow
How cloud I slove it ? @wangg12

**Comment by wangg12** [comment]
How did you compile flow_c and what is your environment info?

**Comment by G-YY** [comment]
My gcc version is 5.4.0 and python 2.7,cuda 10.0,GPU 2080

I run sh init.sh 
running build_ext
cythoning gpu_flow.pyx to gpu_flow.cpp
building 'gpu_flow' extension
/usr/local/cuda-10.0/bin/nvcc -I/home/lab/.conda/envs/py27/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda-10.0/include -I/home/lab/.conda/envs/py27/include/python2.7 -c gpu_flow_kernel.cu -o build/temp.linux-x86_64-2.7/gpu_flow_kernel.o -arch=sm_35 --ptxas-options=-v -c --compiler-options '-fPIC'
ptxas info    : 0 bytes gmem
ptxas info    : Compiling entry function '_Z11flow_kerneliPKfS0_iiPfS1_S1_S1_' for 'sm_35'
ptxas info    : Function properties for _Z11flow_kerneliPKfS0_iiPfS1_S1_S1_
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 28 registers, 384 bytes cmem[0], 36 bytes cmem[2]
gcc -pthread -B /home/lab606/.conda/envs/py27/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/lab/.conda/envs/py27/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda-10.0/include -I/home/lab/.conda/envs/py27/include/python2.7 -c gpu_flow.cpp -o build/temp.linux-x86_64-2.7/gpu_flow.o -Wno-unused-function
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/lab/.conda/envs/py27/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                 from /home/lab/.conda/envs/py27/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/lab/.conda/envs/py27/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from gpu_flow.cpp:449:
/home/lab/.conda/envs/py27/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
g++ -pthread -shared -B /home/lab/.conda/envs/py27/compiler_compat -L/home/lab606/.conda/envs/py27/lib -Wl,-rpath=/home/lab/.conda/envs/py27/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-2.7/gpu_flow_kernel.o build/temp.linux-x86_64-2.7/gpu_flow.o -L/usr/local/cuda-10.0/lib64 -L/home/lab/.conda/envs/py27/lib -Wl,-R/usr/local/cuda-10.0/lib64 -lcudart -lpython2.7 -o /home/lab/mx-DeepIM/lib/flow_c/gpu_flow.so
Do you know how to slove it?Thank you.

**Comment by G-YY** [comment]
My gcc version is 5.4.0 and python 2.7,cuda 10.0,GPU 2080

I run sh init.sh
running build_ext
cythoning gpu_flow.pyx to gpu_flow.cpp
building 'gpu_flow' extension
/usr/local/cuda-10.0/bin/nvcc -I/home/lab/.conda/envs/py27/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda-10.0/include -I/home/lab/.conda/envs/py27/include/python2.7 -c gpu_flow_kernel.cu -o build/temp.linux-x86_64-2.7/gpu_flow_kernel.o -arch=sm_35 --ptxas-options=-v -c --compiler-options '-fPIC'
ptxas info : 0 bytes gmem
ptxas info : Compiling entry function 'Z11flow_kerneliPKfS0_iiPfS1_S1_S1' for 'sm_35'
ptxas info : Function properties for Z11flow_kerneliPKfS0_iiPfS1_S1_S1
0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info : Used 28 registers, 384 bytes cmem[0], 36 bytes cmem[2]
gcc -pthread -B /home/lab/.conda/envs/py27/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/lab/.conda/envs/py27/lib/python2.7/site-packages/numpy/core/include -I/usr/local/cuda-10.0/include -I/home/lab/.conda/envs/py27/include/python2.7 -c gpu_flow.cpp -o build/temp.linux-x86_64-2.7/gpu_flow.o -Wno-unused-function
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/lab/.conda/envs/py27/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
from /home/lab/.conda/envs/py27/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
from /home/lab/.conda/envs/py27/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
from gpu_flow.cpp:449:
/home/lab/.conda/envs/py27/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
#warning "Using deprecated NumPy API, disable it by "
^
g++ -pthread -shared -B /home/lab/.conda/envs/py27/compiler_compat -L/home/lab606/.conda/envs/py27/lib -Wl,-rpath=/home/lab/.conda/envs/py27/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-2.7/gpu_flow_kernel.o build/temp.linux-x86_64-2.7/gpu_flow.o -L/usr/local/cuda-10.0/lib64 -L/home/lab/.conda/envs/py27/lib -Wl,-R/usr/local/cuda-10.0/lib64 -lcudart -lpython2.7 -o /home/lab/mx-DeepIM/lib/flow_c/gpu_flow.so
Do you know how to slove it?Thank you. @wangg12

**Comment by wangg12** [comment]
Try compiling with python3.5+?

**Comment by G-YY** [comment]
> Try compiling with python3.5+?

The same error compiling with 3.6 @wangg12

**Comment by wangg12** [comment]
I can't reproduce this error.  No idea.
