### ISSUE TITLE
I was trying to run the script "preprare_data.sh" but am running into errors

### ISSUE THREAD

**Issue by Okityou** [liyi14/mx-DeepIM#14]
![1542963229 1](https://user-images.githubusercontent.com/44048634/48934915-c9f4a900-ef40-11e8-8e81-44a8e4415dcc.png)
 TypeError: objload() got an unexpected keyword argument 'rescale'
Exception AttributeError: "Render_Py instance has no attribute 'window'" in <bound method Render_Py.__del__ of <lib.render_glumpy.render_py_multi.Ren, Why? I am confused .

**Comment by wangg12** [comment]
Please refer to issue #12
