### ISSUE TITLE
benchvise or benchviseblue

### ISSUE THREAD

**Issue by flowtcw** [liyi14/mx-DeepIM#19]
I find some different in this code. When I open folder, I found some folder named benchviseblue, but when I run the code, they may named benchvise. So I just want to know should I modify benchvise to benchviseblue or benchviseblue to benchvise. Which is the best way?

**Comment by wangg12** [comment]
Use rename all benchviseblue to benchvise, please.

**Comment by flowtcw** [comment]
> Rename all benchviseblue to benchvise, please.

thank you very much!
I see your code setting the seed 2333, haha! interesting!
