### ISSUE TITLE
Results on YCB-video

### ISSUE THREAD

**Issue by tim885** [liyi14/mx-DeepIM#20]
Hi, 
Your work looks great and it certainly improves the performance. Whether do you have results on YCB-video dataset? As PoseCNN reported results on YCB-video, the results after refinement should be interesting. 
Thanks a lot!

**Comment by liyi14** [comment]
We will release a new version of paper on arxiv which includes the results on YCB-Video.

**Comment by liyi14** [comment]
The results on YCB-Video has been released on [arxiv](https://arxiv.org/pdf/1804.00175.pdf)
