### ISSUE TITLE
Exception AttributeError: "Render_Py instance has no attribute 'window'"

### ISSUE THREAD

**Issue by eyildiz-ugoe** [liyi14/mx-DeepIM#23]
During the training which is triggered by the following command:

`python experiments/deepim/deepim_train_test.py --cfg experiments/deepim/cfgs/deepim_flownet_LM_SIXD_v1_all_RFMx4_8epoch.yaml --gpus 0,1,2,3`

the error of:

```
Loading ./data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/ape
Loading ./data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/benchvise
Loading ./data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/camera
Loading ./data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/can
Loading ./data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/cat
Loading ./data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/driller
Loading ./data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/duck
Loading ./data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/eggbox
Loading ./data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/glue
Loading ./data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/holepuncher
Loading ./data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/iron
Loading ./data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/lamp
Loading ./data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/phone
************Finish loading models*************
[x] Window creation failed
Exception AttributeError: "Render_Py instance has no attribute 'window'" in <bound method Render_Py.__del__ of <lib.render_glumpy.render_py_multi.Render_Py instance at 0x7f31580d6998>> ignored

```

is thrown.  Yes, I did install glumpy from source by executing the following:

```
git clone https://github.com/glumpy/glumpy.git
cd glumpy
python setup.py install
```

Executing this:

`python lib/render_glumpy/render_py_multi.py`

however, gives an error:

```
 Traceback (most recent call last):
   File "lib/render_glumpy/render_py_multi.py", line 13, in <module>
     from lib.pair_matching.RT_transform import quat2mat
 ImportError: No module named lib.pair_matching.RT_transform
```

which indicates that something isn't installed properly. However, I cannot think of anything since I did everything as told. How can we possible disable all this GUI-related stuff? We don't need this, it serves no purpose while training and testing, can't we just disable this?

**Comment by eyildiz-ugoe** [comment]
Commenting out every single line that involes GUI operations and windows in `render_py_multi.py` seems to have solved the problem.

**Comment by joefriel** [comment]
> Commenting out every single line that involes GUI operations and windows in `render_py_multi.py` seems to have solved the problem.

I am trying to run deepIM in a notebook (on google colab) and glumpy is not compatible with notebooks (see https://glumpy.readthedocs.io/en/latest/faq.html).  

I successfully ran the first step in 'prepare_data.sh' ("python toolkit/LM6d_devkit/LM6d_2a_adapt_images.py"), but immediately hit GUI ('window') issues on the next step.  Did you ever succeed in running deepIM totally without glumpy?  Thanks

**Comment by Cryptiex** [comment]
I'm facing the same problem. 
Calling _python lib/render_glumpy/render_py_multi.py_ yields the following error:

ImportError: No module named lib.pair_matching.RT_transform

Is there any workaround @wangg12 @liyi14 ?

**Comment by wangg12** [comment]
Are you running it through a monitor or ssh?

**Comment by Cryptiex** [comment]
I ran it via SSH

**Comment by BigBuffa1o** [comment]
> > Commenting out every single line that involes GUI operations and windows in `render_py_multi.py` seems to have solved the problem.
> 
> I am trying to run deepIM in a notebook (on google colab) and glumpy is not compatible with notebooks (see https://glumpy.readthedocs.io/en/latest/faq.html).
> 
> I successfully ran the first step in 'prepare_data.sh' ("python toolkit/LM6d_devkit/LM6d_2a_adapt_images.py"), but immediately hit GUI ('window') issues on the next step. Did you ever succeed in running deepIM totally without glumpy? Thanks
> 
> (Edit: I was able to get this working by installing a virtual display, glumpy no longer complains) !apt-get install xvfb !pip -q install pyvirtualdisplay
> 
> from pyvirtualdisplay import Display display = Display(visible=0, size=(1024, 768)) display.start() import os os.environ["DISPLAY"] = ":" + str(display.display) + "." + str(display.screen)

Where do you put these code? I meet the same problem and try to add these code in render_py.py and error still occurs, thanks in advance!
