### ISSUE TITLE
Prepare_data.sh does not work

### ISSUE THREAD

**Issue by Cryptiex** [liyi14/mx-DeepIM#26]
When calling prepare_data.sh the following output occurs:

####### Prepare LM6d_refine #######
target path: /media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/data/observed
Loading /media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/ape
Loading /media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/benchviseblue
Loading /media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/bowl
Loading /media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/camera
Loading /media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/can
Loading /media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/cat
Loading /media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/cup
Loading /media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/driller
Loading /media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/duck
Loading /media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/eggbox
Loading /media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/glue
Loading /media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/holepuncher
Loading /media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/iron
Loading /media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/lamp
Loading /media/deeplearner2/DataSSD/PycharmProjects/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/phone
************Finish loading models*************

From there on, the function does not proceed. I think it has something to do with glumpy, even though I installed glumpy from the GitHub repo.

**Comment by wangg12** [comment]
What is the specific error? Did you run it on a monitor connected to the machine?

**Comment by Cryptiex** [comment]
I ran it via SHH. I tried running it on a machine with a monitor directly connected to it, which produced at least an error message

**Comment by wangg12** [comment]
@Cryptiex Currently you can only run it on the monitor.

**Comment by hillaric** [comment]
<img width="361" alt="无标题1" src="https://user-images.githubusercontent.com/50513602/57605112-792d4700-7598-11e9-9bcd-a5968261d076.png">

**Comment by wangg12** [comment]
Glumpy does not support headless rendering, thus you can only run the rendering with a monitor connected and make sure $DISPLAY is zero, i.e., SSH X forwarding is not supported.

**Comment by G-YY** [comment]
I run the Prepare_data.sh, but met the following error:
IOError: [Errno 2] No such file or directory: '/home/lab/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/ape/textured.obj'
