### ISSUE TITLE
prepare_data.sh

### ISSUE THREAD

**Issue by hillaric** [liyi14/mx-DeepIM#29]

**Comment by hillaric** [comment]
when I run the  "python lib/render_glumpy/render_py_multi.py", I meet this problem, can you help me?
************Finish loading models*************
[x] Window creation failed
Exception AttributeError: "Render_Py instance has no attribute 'window'" in <bound method Render_Py.__del__ of <__main__.Render_Py instance at 0x7f0985a75638>> ignored

**Comment by wangg12** [comment]
What's your output of `echo $DISPLAY`?

**Comment by hillaric** [comment]
:10.0




Hillaric Zhou - 周廣源, Master

Ecole Centrale de Pekin
Sino-French Engineer School
中法工程师学院
Beihang University
北京航空航天大学
Xueyuan Road 37#，HaiDian District, Beijing，China
中国，北京，海淀区，学院路37号
Post Code，100191
Tel : 158 1068 8708
WeChat ID : hillaric
On 05/13/2019 11:29, Gu Wang wrote:

What's your output of echo $DISPLAY?

**Comment by hillaric** [comment]
10.0

**Comment by wangg12** [comment]
Please refer to #26

**Comment by wangg12** [comment]
Headless rendering is currently not supported.
