### ISSUE TITLE
Prepare data files missing

### ISSUE THREAD

**Issue by dmasmont** [liyi14/mx-DeepIM#3]
Hello,
The scripts specified in "prepare_data.md" to prepare the data for ModelNet, T-LESS, and Synthetic with occlusion are missing in the toolkit folder. Will they be available?

Thank you,
Daniel

**Comment by wangg12** [comment]
@dmasmont You could check out [my repo](https://github.com/wangg12/mx-DeepIM). The scripts are there but you may need to do some minor modification to them to make it work for you.
