### ISSUE TITLE
train_and _test_deepim_ape.sh

### ISSUE THREAD

**Issue by hillaric** [liyi14/mx-DeepIM#32]
mxnet.base.MXNetError: [16:02:00] src/io/local_filesys.cc:199: Check failed: allow_null  LocalFileSystem::Open "./output/deepim_release/deepim_flownet_LM_SIXD_v1_ape_RFMx4_8epoch/PoseCNN_val_/../train__train_/flownet_SE3_ex_LM6d_v1-0008.params": No such file or directory

**Comment by Cryptiex** [comment]
Can you check whether the RESUME flag is set to True or False in your cfg at `experiments/deepim/cfgs`?

**Comment by wangg12** [comment]
I guess you are testing the pretrained model without training, you need to manually put the pretrained model into the desired folder.
