### ISSUE TITLE
Type of Flownet

### ISSUE THREAD

**Issue by Cryptiex** [liyi14/mx-DeepIM#33]
Did you use the pretrained version of FlowNetSimple or did you retrain it with custom data? I tried using DeepIM on my own dataset and the resulting flow is really bad.

**Comment by wangg12** [comment]
The general pre-trained FlowNet-S should be OK, we do not re-train it with custom data.

**Comment by Cryptiex** [comment]
How did you obtain a pre-trained FlowNetSimple in MXNet? All I found was PyTorch and Caffe checkpoints.

**Comment by Cryptiex** [comment]
How did you obtain the _flownet-0000.params_ file? All the FlowNetSimple projects I found either used Caffe or PyTorch.

**Comment by wangg12** [comment]
@Cryptiex It was converted from the official caffe version, we borrowed from [https://github.com/msracver/Deep-Feature-Flow#demo, the Baidu Yun link](https://github.com/msracver/Deep-Feature-Flow#demo). 

You can also find other download options from our README.
