### ISSUE TITLE
Time of test

### ISSUE THREAD

**Issue by hillaric** [liyi14/mx-DeepIM#34]
How long it take if I just run the test.py by using the Trained weights in the Google Drive? Thank you for your time

**Comment by wangg12** [comment]
It depends on your machine. We've reported the test time in our paper. Please check it.

**Comment by chenerg** [comment]
Sorry, I can't find the test time in ECCV paper. Would you please point out which part includes the test time?

**Comment by wangg12** [comment]
It is near the end of Section 4.1.
