### ISSUE TITLE
build.sh

### ISSUE THREAD

**Issue by hillaric** [liyi14/mx-DeepIM#35]
no module named gpu_flow

**Comment by hillaric** [comment]
could somebody can help me?

**Comment by hillaric** [comment]
(mxnet) jmj@ubuntu:/media/jmj/tiyuju-2T/mx-DeepIM1/mx-DeepIM$ sh init.sh 
running build_ext
skipping 'gpu_flow.cpp' Cython extension (up-to-date)
(mxnet) jmj@ubuntu:/media/jmj/tiyuju-2T/mx-DeepIM1/mx-DeepIM$

**Comment by hillaric** [comment]
why it does not run correctement, the probelm of gcc ?

**Comment by hillaric** [comment]
why does it not run correctement, the probelm of gcc ?

**Comment by wangg12** [comment]
gcc could be the reason.

**Comment by G-YY** [comment]
> why does it not run correctement, the probelm of gcc ?

How to slove it? I met the same error

**Comment by Cryptiex** [comment]
Replace https://github.com/liyi14/mx-DeepIM/blob/7a715477b066528b67a8246f28fa8bac79180051/lib/flow_c/flow.py#L11 by `sys.path.insert(1, cur_dir)`
