### ISSUE TITLE
IOError in prepare_data.sh

### ISSUE THREAD

**Issue by G-YY** [liyi14/mx-DeepIM#36]
When I run the prepare_data.sh, I met the following error and I cloud not find the /ape/textured.obj file.
sh prepare_data.sh
####### Prepare LM6d_refine #######
target path: /home/lab/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/data/observed
Loading /home/lab/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/ape
Traceback (most recent call last):
  File "toolkit/LM6d_devkit/LM6d_2a_adapt_images.py", line 244, in <module>
    main()
  File "toolkit/LM6d_devkit/LM6d_2a_adapt_images.py", line 116, in main
    render_machine = Render_Py(model_dir, classes, K, width, height, ZNEAR, ZFAR)
  File "/home/lab/mx-DeepIM/toolkit/LM6d_devkit/../../lib/render_glumpy/render_py_multi.py", line 74, in __init__
    "{}/textured.obj".format(model_folder), rescale=False
  File "/home/lab/.conda/envs/py27/lib/python2.7/site-packages/glumpy/data/__init__.py", line 81, in objload
    for lineno,line in enumerate(open(filename)):
IOError: [Errno 2] No such file or directory: '/home/lab/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/ape/textured.obj'
Exception AttributeError: "Render_Py instance has no attribute 'window'" in <bound method Render_Py.__del__ of <lib.render_glumpy.render_py_multi.Render_Py instance at 0x7f372d8b9b90>> ignored

**Comment by G-YY** [comment]
I have sloved the problem.

**Comment by G-YY** [comment]
I want to estimate multi-object pose, how to make the label? @wangg12

**Comment by wangg12** [comment]
DeepIM is used for pose refinement, not estimation.

**Comment by harshalsonioo1** [comment]
How did you solve this issue? I am stuck on same issue.
