### ISSUE TITLE
Pixel means in config file

### ISSUE THREAD

**Issue by Cryptiex** [liyi14/mx-DeepIM#38]
In the config file there is a PIXEL_MEANS parameter.

Is this just the BGR pixel mean of the training set used for normalization?

**Comment by wangg12** [comment]
It is RGB means actually, it will be converted into BGR in the code.

**Comment by Cryptiex** [comment]
Do I need to adjust the means according to my own dataset?

**Comment by wangg12** [comment]
It is up to you. We use the default ImageNet means. You can try with the means of your own dataset. And please let me know whether it is better to use dataset specific means.
