### ISSUE TITLE
split validation / train

### ISSUE THREAD

**Issue by speyside42** [liyi14/mx-DeepIM#4]
Hi!

thanks for open sourcing the code!

In LM6d_0b_split_train_val_set_bowl_cup.py, you excluded everything but bowl and cup. Why?

        if not class_name in ['bowl', 'cup']:
             continue

PS: The data preparation is a bit tedious. Maybe you could avoid copying data and remove some of the absolute paths in the code.

**Comment by wangg12** [comment]
@speyside42 bowl and cup are not used in other works and they don't have the train/val split , so LM6d_0b_split_train_val_set_bowl_cup.py is also not used in our work. You could simply skip this script.
The script is just for splitting train/val of  bowl and cup by taking randomly 15% for train and 85% for val. the train/val split for other classes could be find in [Google drive](https://drive.google.com/drive/folders/1sdBoEmO8UXnkXRoaGUFUai6E3Od6O2e-).

You are welcomed to propose a PR for data preparation to avoid copying data.

**Comment by speyside42** [comment]
ah, thanks for the explanation. I have split all objects with your script by now, but I guess this should not matter much. PR maybe, if I get useful results of your code :)

**Comment by speyside42** [comment]
it is actually training now and PointMatchingLoss is decreasing :-) 

Besides the issues with the paths, only two minor points:

- README does not mention that VOC2012 is required for training. 
- Missing dependencies: tqdm, hickle

**Comment by wangg12** [comment]
@speyside42 README and dependency are updated.
