### ISSUE TITLE
Is object segmentation mask the nessarcy input for DeepIM?

### ISSUE THREAD

**Issue by Hao-HUST** [liyi14/mx-DeepIM#43]
Hi, thanks for sharing your work.

I am wondering that is a predicted segmentation maks from an initial pose estimation algorithm, like PoseCNN, the necessary input for DeepIM?

Or in other words, can some other object pose estimation methods without object segmentation prediction, like yolo-6D pose estimation(https://arxiv.org/abs/1711.08848), take the initial poes estimation as input for DeepIM?

Thanks!

**Comment by wangg12** [comment]
It is not necessay. And in our implementation, the initial mask of the observed image is simply the bound box area (which can be the predicted 2d detections or the projected box of the intial pose).
