### ISSUE TITLE
evaluation the model

### ISSUE THREAD

**Issue by alexey-kashapov** [liyi14/mx-DeepIM#44]
Hi!
I want to use your trained model on LINEMOD dataset to get 6DOF position of my own object.
I have a 3d model and pictures for testing. Do I need something else?
How can I do this?

**Comment by wangg12** [comment]
You need to provide initial poses for each test image (DeepIM is for pose refinement), and then follow the data preparation steps (see toolkit) to convert the data format to be compatible with the model.

**Comment by alexey-kashapov** [comment]
Thank you for reply!
Also, How can I evaluate your already trained model for my new 3d-object?

**Comment by wangg12** [comment]
If your "new 3d object" is not in LINEMOD dataset, maybe you need to train your own DeepIM model.
Otherwise you can just follow the guides of this repo for standard LINEMOD objects.

**Comment by alexey-kashapov** [comment]
Thank you so much!
I have an engineering problem - to find the rotation angle of the object in a 2D image using its 3d model.
We know the exact position of the object and its maximum sizes. The single problem is to find a rotation angle - yaw angle.
May you give me some advice on what's a technique to use? Because for this task deep learning is looking overkilled.
Thank you in advance!

**Comment by wangg12** [comment]
A naive approach is to render your 3d model on some yaw angles (uniformly or randomly) and try to match the rendered image to the object in the 2D image. You can also try some traditional template matching (if the model is textureless) or local-feature matching (if the model is rich in texture) methods. You could also try to render a lot of synthetic images and train a deep learning based pose estimation or refinement model.

**Comment by alexey-kashapov** [comment]
@wangg12 
Thank you!
