### ISSUE TITLE
About refine lineMOD

### ISSUE THREAD

**Issue by Sunweijun333** [liyi14/mx-DeepIM#45]
If I want to optimize LINEMOD, is it just that I only need to give the test picture and the corresponding initial pose?

**Comment by wangg12** [comment]
Yes. And you need to prepare the data to make it compatible with the data loader given your initial poses.

**Comment by Sunweijun333** [comment]
ok，I will try ，thank you！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Gu Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月29日(星期二) 晚上9:04
收件人:&nbsp;"liyi14/mx-DeepIM"<mx-DeepIM@noreply.github.com&gt;;
抄送:&nbsp;"夜静∮觅云溪"<2318085206@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liyi14/mx-DeepIM] About refine lineMOD (#45)




Yes. And you need to prepare the data to make it compatible with the data loader given your initial poses.

**Comment by bbg-pjg** [comment]
@wangg12  
How did you get the .mat file in bulk from the POSECNN results?
