### ISSUE TITLE
About .mat file.

### ISSUE THREAD

**Issue by Sunweijun333** [liyi14/mx-DeepIM#46]
I see that there are not only Pose but also "rois, poses_icp, labels" in the .mat file. Can you explain the meaning of this? I think this pose via icp is not necessary, just enter 'pose', can this be? ,Looking forward to your reply

**Comment by wangg12** [comment]
Yes. The poses_icp is for the results of ICP refined poses in the PoseCNN paper. If you are using your own initial pose results, you just need to provide the class labels and the poses for each image. And it is not necessary to be in a `.mat` format.

**Comment by Sunweijun333** [comment]
@wangg12 Which pose is used in your code as the initial pose?

**Comment by wangg12** [comment]
The original output poses of PoseCNN (without ICP refinement) [https://github.com/liyi14/mx-DeepIM/blob/master/toolkit/LM6d_3_gen_PoseCNN_pred_rendered.py#L120](https://github.com/liyi14/mx-DeepIM/blob/master/toolkit/LM6d_3_gen_PoseCNN_pred_rendered.py#L120).

**Comment by Sunweijun333** [comment]
I found that in the .mat file, the "label" value should be mask, but I showed that the label you provided is slightly different from the corresponding mask of the original LINEMOD. Can you explain why? thank you very much

**Comment by wangg12** [comment]
I think the labels of PoseCNN results are the predicted semantic masks, and what do you mean by `the label you provided`?

**Comment by Sunweijun333** [comment]
If I put an initial pose of the LINEMOD I got into the ‘pose’ in the mat file, can I refine it directly?

**Comment by wangg12** [comment]
Yes, you can refine it directly if you also know the class (plus the corresponding 3D model) of that pose. The other informations like bbox/mask can be generated from the pose and its 3D model.

**Comment by Sunweijun333** [comment]
In other words, your .mat file provides bbox/mask/pose. The code only uses these three conditions. Are the other two poses not used?

**Comment by wangg12** [comment]
Which other two poses specifically? I don't quite understand.

**Comment by Sunweijun333** [comment]
Poses_icp and Poses_refined

**Comment by Sunweijun333** [comment]
![image](https://user-images.githubusercontent.com/42403620/67947353-70036580-fc1e-11e9-9579-714edfe05a65.png)

**Comment by wangg12** [comment]
You are right, the other two are not needed.

**Comment by Sunweijun333** [comment]
OK Thanks very very much!
