### ISSUE TITLE
Ask me to deal with the problem of optimizing LINEMOD

### ISSUE THREAD

**Issue by Sunweijun333** [liyi14/mx-DeepIM#49]
What I am going to do now is to optimize LINEMOD. Just like you optimize PoseCNN results, I am optimizing the pose generated by other methods. I think because the dataset and the object are the same, I just need to change the pose to what I want. The optimized posture is just fine. Is this understanding wrong? Looking forward to your reply

**Comment by wangg12** [comment]
In general, you can refine the pose results of any method.
