### ISSUE TITLE
Prepare Data.sh 

### ISSUE THREAD

**Issue by harshalsonioo1** [liyi14/mx-DeepIM#51]
I have downloaded and kept the files as instructed. However, it is throwing the same errors. Any idea?

`####### Prepare LM6d_refine #######
target path: /content/drive/My Drive/Project811_Folder/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/data/observed
Loading /content/drive/My Drive/Project811_Folder/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/ape
Loading /content/drive/My Drive/Project811_Folder/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/benchvise
Traceback (most recent call last):
  File "toolkit/LM6d_devkit/LM6d_2a_adapt_images.py", line 216, in <module>
    main()
  File "toolkit/LM6d_devkit/LM6d_2a_adapt_images.py", line 112, in main
    render_machine = Render_Py(model_dir, classes, K, width, height, ZNEAR, ZFAR)
  File "/content/drive/My Drive/Project811_Folder/mx-DeepIM/toolkit/LM6d_devkit/../../lib/render_glumpy/render_py_multi.py", line 72, in __init__
    vertices, indices = data.objload("{}/textured.obj".format(model_folder), rescale=False)
  File "/usr/local/lib/python2.7/dist-packages/glumpy/data/__init__.py", line 81, in objload
    for lineno,line in enumerate(open(filename)):
IOError: [Errno 2] No such file or directory: '/content/drive/My Drive/Project811_Folder/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/benchvise/textured.obj'
Exception AttributeError: "Render_Py instance has no attribute 'window'" in <bound method Render_Py.__del__ of <lib.render_glumpy.render_py_multi.Render_Py instance at 0x7f0201a4b950>> ignored`

**Comment by wangg12** [comment]
> IOError: [Errno 2] No such file or directory: '/content/drive/My Drive/Project811_Folder/mx-DeepIM/toolkit/LM6d_devkit/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/models/benchvise/textured.obj
