### ISSUE TITLE
Download is too slow

### ISSUE THREAD

**Issue by EasonEdison** [liyi14/mx-DeepIM#54]
I download test.zip from http://ptak.felk.cvut.cz/6DB/public/datasets/hinterstoisser/
but it is so slow that I need 7days to do it.
Any else way to get test.zip ?  Google Drive or Baidu NetDisk ?
Thank you!

**Comment by wangg12** [comment]
Maybe you can contact the dataset provider. (http://cmp.felk.cvut.cz/sixd/challenge_2017/#datasets)
