### ISSUE TITLE
Data loss

### ISSUE THREAD

**Issue by renjiahao0928** [liyi14/mx-DeepIM#59]
I can not find the dataset from **http://ptak.felk.cvut.cz/6DB/public/datasets/hinterstoisser/**,at the same time,I can't downloaded `test`,where can I find it ? Thanks

**Comment by wangg12** [comment]
It seems they don't host the data on this link anymore. You can download the data from https://bop.felk.cvut.cz/datasets/. But the annotation format is a little different (for example, .yml files vs. .json files).

**Comment by wangg12** [comment]
I have updated the code according to the new link. Let me know if you have any problems.
