### ISSUE TITLE
How to use the main() function in zoom_flow.py to check the zoomflow operator?

### ISSUE THREAD

**Issue by z6491679** [liyi14/mx-DeepIM#62]
hi,I have changed the file path to my own dataset,but the figure shows out are all black, do I have to change something else to make this main() function work? The dataset is linemod ape.

        img_idx[idx] = 1
        v_image_rendered[idx] = cv2.imread(
            cur_dir + "/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/data/rendered/ape/{:06}_1-color.png".format(img_idx[idx]),
            cv2.IMREAD_COLOR,
        ).transpose([2, 0, 1])

        v_image_real[idx] = cv2.imread(
            cur_dir + "/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/data/observed/01/{:06}-color.png".format(img_idx[idx]),
            cv2.IMREAD_COLOR,
        ).transpose([2, 0, 1])

        v_depth_real[idx, 0] = (
            cv2.imread(
                cur_dir + "/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/data/gt_observed/ape/{:06}-depth.png".format(img_idx[idx]),
                cv2.IMREAD_UNCHANGED,
            )
            / 10000.0
        )

        v_depth_rendered[idx, 0] = (
            cv2.imread(
                cur_dir + "/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/data/rendered/ape/{:06}_1-depth.png".format(img_idx[idx]),
                cv2.IMREAD_UNCHANGED,
            )
            / 10000.0
        )

        pose_real_path = cur_dir + "/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/data/gt_observed/ape/{:06}-pose.txt".format(img_idx[idx])

        pose_est_path = cur_dir + "/../../data/LINEMOD_6D/LM6d_converted/LM6d_refine/data/rendered/ape/{:06}_0-pose.txt".format(img_idx[idx])

the figure shows like this:
![无标题](https://user-images.githubusercontent.com/3224805/101769202-93872800-3b21-11eb-80e7-4b786a2831b8.png)

many thanks!

**Comment by z6491679** [comment]
I want to check this operator because I want to change the input size from 640*480 to other size, but when I finished preparing the data and train, there are always some bugs in this operator, so i wonder if there are something else beside the flownet input size that I should change to make this whole train work?

**Comment by wangg12** [comment]
Well, the code under __main__ is using data for YCB-Video. To make it work for LINEMOD, you need to change YCB-Video K to the LINEMOD K and the depth factor from 10000 to 1000.
