### ISSUE TITLE
How to avoid T_src = [0,0,0] when data_batch update?

### ISSUE THREAD

**Issue by z6491679** [liyi14/mx-DeepIM#63]
Hi, I have another problem when training my own data, I found that when I send my initial src_pose to module.py fit function:
  `for iter_idx in range(train_iter_size):`
    `     self.forward_backward(data_batch)`
 `preds = self._curr_module.get_outputs(False)`
` self.update()`
 `print("module.py iter_idx:", iter_idx, train_iter_size)`
 `if iter_idx != train_iter_size - 1:`
 `data_batch = interBatchUpdater.forward(data_batch, preds, config)`

the data_batch have chances to  output src_pose that T_src = [0,0,0],  this will cause bug in next iteration in RT_transform below:
![无标题1](https://user-images.githubusercontent.com/3224805/101978490-50979280-3c90-11eb-8759-725595cd24b9.png)
I also wonder what differences between this 'camera' and 'camera_new' branch? if I set 'camera_new' flag, may the T_src be [0,0,0]?

many thanks!

**Comment by wangg12** [comment]
Hi, you can do a clip on T_src[2] with a minimal value based on the distance from the camera to the object (for example 0.1 for LINEMOD, because LINEMOD's minimal distance is about 0.5).
