### ISSUE TITLE
Clarification on depth images

### ISSUE THREAD

**Issue by Gan868611** [liyi14/mx-DeepIM#64]
hi, i intend to handle my project with this algo based on RGB images only, however when i go through the `prepare_data.sh` i saw that one of the [file](https://github.com/liyi14/mx-DeepIM/blob/master/toolkit/LM6d_devkit/LM6d_2a_adapt_images.py#L98) actually takes in depth images. But this in thread #10 , it was mentioned that only RGB is needed, so i am a bit confused, can anyone help me?

**Comment by wangg12** [comment]
The depth files were kept, but they were not used in the main code.
